### ISSUE TITLE
IANA attribute names

### ISSUE THREAD

**Issue by troyronda** [mattrglobal/jwm#41]
Section 7.1

> Because a core goal of this
   specification is for the resulting representations to be compact, it
   is RECOMMENDED that the name be short - that is, not to exceed 8
   characters without a compelling reason to do so. 

Note that some of the attribute names that follow this paragraph exceed 8 characters.
- thread_id
- created_time
- expires_time

I was also somewhat curious on the semantic difference between some of the seemingly overlapping fields with JWT (e.g., `exp`). Perhaps this is stylistic or due to the usage of the term "token" or "issuer" in the JWT definitions of the field names?

**Comment by llorllale** [comment]
Regarding the last two - I wonder why we don't reuse the standard claims already registered?

**Comment by tplooker** [comment]
I have had discussion about whether we should continue the pattern of concise names in JWM that is present with claim names in JWT. The obvious tradeoff here is human readability.

For clarity @llorllale a JWM does not have claims, instead it has attributes so the intention is for JWM to have its own IANA registry called the JWM attribute registry much like JWT has the [JWT claims registry](https://www.iana.org/assignments/jwt/jwt.xhtml) and yes there would be overlap between these two registries in certain areas, however I believe this is better then us trying to overload one registry with a whole bunch of conflicting concepts.

**Comment by troyronda** [comment]
@tplooker I thought it was interesting that section 7.1 in the JWM document recommended 8 characters maximum. I assume this section is copied from a template.

Do you need some explanation text rationalizing the longer names?

**Comment by tplooker** [comment]
@troyronda correct it was an oversight, I will fix :)
