### ISSUE TITLE
Disallow 'flattened' form of JWM?

### ISSUE THREAD

**Issue by TelegramSam** [mattrglobal/jwm#47]
The `compact` form is useful for URL safe transfer, and the `general` form is useful for multi-recipient messages. The `flattened` form falls in an odd gap between these, offering neither of those advantages. Can JWM disallow this form?

**Comment by tplooker** [comment]
Agreed, there is marginal utility in supporting the flattened form of JWS and JWE.

**Comment by kdenhartog** [comment]
Only reason I've seen this used is if people want to stick with JSON structures (for typing simplicity likely) while supporting single recipients. I'm good with removing this as well.
