### ISSUE TITLE
reply_to property value definition seems wrong

### ISSUE THREAD

**Issue by kdenhartog** [mattrglobal/jwm#54]
> ... is a case-sensitive string containing an array of case-sensitive strings ...

This seems incorrect. It would lead me to believe this is what the spec is after

```json
{
    "reply_to": "["didUrl1", "didUrl2"]"
}
```

Rather I think it intends for the json to look like this:

```json
{
    "reply_to": ["didUrl1", "didUrl2"]
}
```

Which means the text should be updated to say this:

>  ... is an array of case-sensitive strings ...

**Comment by tplooker** [comment]
This issued was fixed in #55
